### PR TITLE
Fixed getting email with all other attributes

### PR DESCRIPTION
**Pull request by vyskocilpavel**
Add the possibility to get an email in response.

Please add a higher priority. It is required for using oauth2-linkedin as a provider for some other modules.

Thanks

### CODE REVIEW

**Comment by vyskocilpavel** [comment]
@stevenmaguire Are you OK with this PR? Can you review and merge it?

Thanks,
Pavel

**Comment by stevenmaguire** [comment]
@vyskocilpavel thanks for the patience here. If the current design includes setting the email when  constructing the resource owner object, why not set the email in the response array then and not overwrite this parent toArray method?

**Comment by vyskocilpavel** [comment]
Hi @stevenmaguire,
I used the simplest solution, but I will rewrite it.

I will let you know after I push it. Thanks.

**Comment by vyskocilpavel** [comment]
I rewrote it to modified the response before creating the ResourceOwner, so the email is now available in response.

Best,
Pavel

**Pull request merged**
